import React from "react";
import Campaign from "../component/brand/Campaign";
import Layout from "../component/layouts/layout";

const campaign = () => {
  return (
    <>
      {/* <Head>
        <title>Influencer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
          integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm"
          crossOrigin="anonymous"
        ></link>
      </Head> */}

      <Layout>
        <Campaign />
      </Layout>
    </>
  );
};

export default campaign;
