import Image from "next/image";
import Head from "next/head";
import styles from "../styles/Home.module.css";
import Layout from "../component/layouts/layout";
import Script from "next/script";
import Slider from "../component/home/slider/Slider";
import Testimonial from "../component/home/testimonial/Testimonial";
import WhyUs from "../component/home/whyUs/WhyUs";
import Agencies from "../component/home/agencies/Agencies";
import Contact from "../component/home/contact/Contact";

export default function Home() {
  return (
    <>
      <Head>
        <title>Influencer</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link
          rel="stylesheet"
          href="https://use.fontawesome.com/releases/v5.15.4/css/all.css"
          integrity="sha384-DyZ88mC6Up2uqS4h/KRgHuoeGwBcD4Ng9SiP4dIRy0EXTlnuz47vAwmeGwVChigm"
          crossOrigin="anonymous"
        ></link>
      </Head>

      <Layout>
        <Slider/>
        <WhyUs/>
        <Agencies/>
        <Testimonial/>
        <Contact/>
        </Layout>
    </>
  );
}
